# K-Nearest Neighbors

## 1.환경준비

### (1) Import

In [2]:
#라이브러리들을 불러오자.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

### (2) data loading

In [3]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv'
data = pd.read_csv(path)

|	변수	|	설명	|
|	----	|	----	|
|	**medv**	|	**타운별 집값(중위수), target**	|
|	crim	|	범죄율	|
|	zn	|	25,000 평방피트를 초과한 거주지역 비율	|
|	indus	|	비소매상업지역 면적 비율, 편의시설(관공서, 주요 시설)	|
|	chas	|	찰스강변 위치(범주 : 강변1, 아니면 0)	|
|	nox	|	일산화질소 농도	|
|	rm	|	주택당 방 수	|
|	age	|	1940년 이전에 건축된 주택의 비율	|
|	dis	|	직업센터의 거리	|
|	rad	|	방사형 고속도로까지의 거리	|
|	tax	|	재산세율	|
|	ptratio	|	학생/교사 비율	|
|	black	|	인구 중 흑인 비율	|
|	lstat	|	인구 중 하위 계층 비율	|

## 2.데이터 이해

### (1) 둘러보기

In [4]:
# 상/하위 몇개 행을 살펴 봅시다.
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [5]:
# 각 칼럼의 타입을 살펴 봅시다.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

## 3.데이터 준비

### (1) 데이터 정리

In [6]:
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [7]:
data.drop(['black'], axis = 1, inplace = True)

### (2) 데이터분할1 : x, y 나누기

In [8]:
target = 'medv'
x = data.drop(target, axis=1)
y = data.loc[:, target]

### (3) NA 조치

### (4) 가변수화

### (5) 데이터분할2 : train : validation 나누기

In [9]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3, random_state = 2022)

### (6) Scaling
KNN 알고리즘을 적용하기 위해서는 스케일링을 해야 합니다.

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() #선언
x_train_s1 = scaler.fit_transform(x_train) # fit_transform : fit + transform
x_val_s1 = scaler.transform(x_val) #적용만

In [11]:
from sklearn.preprocessing import StandardScaler

scaler2 = StandardScaler()
x_train_s2 = scaler2.fit_transform(x_train)
x_val_s2 = scaler2.transform(x_val)

In [12]:
x_train_s1 = pd.DataFrame(x_train_s1, columns = list(x))
x_train_s2 = pd.DataFrame(x_train_s2, columns = list(x))

In [13]:
x.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,37.970000

In [14]:
x_train.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat
count,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000
mean,3.204705,11.478814,10.756073,0.070621,0.548530,6.309133,67.485311,3.900144,9.039548,397.790960,18.373164,12.129209
std,8.554879,22.969625,6.894126,0.256554,0.115102,0.689033,27.894307,2.113877,8.413440,163.905474,2.191546,6.739158
min,0.006320,0.000000,0.460000,0.000000,0.389000,3.863000,6.000000,1.129600,1.000000,188.000000,12.600000,1.730000
25%,0.071848,0.000000,4.935000,0.000000,0.448000,5.889500,42.950000,2.168250,4.000000,277.000000,17.000000,6.735000
50%,0.219655,0.000000,8.350000,0.000000,0.524000,6.209000,74.850000,3.361800,5.000000,329.500000,18.850000,10.925000
75%,2.588280,20.000000,18.100000,0.000000,0.614000,6.618750,93.875000,5.226975,8.000000,437.000000,20.200000,15.820000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.725000,100.000000,10.710300,24.000000,711.000000,22.000000,37.970000

In [15]:
x_train_s1.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat
count,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000,354.000000
mean,0.035949,0.114788,0.377422,0.070621,0.330976,0.503112,0.654099,0.289180,0.349546,0.401130,0.614166,0.286954
std,0.096155,0.229696,0.252717,0.256554,0.238801,0.141718,0.296748,0.220639,0.365802,0.313395,0.233143,0.185959
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000737,0.000000,0.164040,0.000000,0.122407,0.416804,0.393085,0.108411,0.130435,0.170172,0.468085,0.138107
50%,0.002398,0.000000,0.289223,0.000000,0.280083,0.482517,0.732447,0.232989,0.173913,0.270554,0.664894,0.253725
75%,0.029021,0.200000,0.646628,0.000000,0.466805,0.566794,0.934840,0.427670,0.304348,0.476099,0.808511,0.388797
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
x_train_s2.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat
count,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02,3.540000e+02
mean,-1.379938e-17,7.025140e-17,8.969598e-17,-1.332895e-17,-3.048409e-16,-6.443371e-16,-1.793920e-16,6.711518e-17,-1.129040e-17,-5.017957e-17,3.070363e-16,2.195356e-16
std,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00,1.001415e+00
min,-3.743960e-01,-5.004462e-01,-1.495570e+00,-2.756589e-01,-1.387952e+00,-3.555120e+00,-2.207344e+00,-1.312501e+00,-9.569127e-01,-1.281763e+00,-2.638016e+00,-1.545286e+00
25%,-3.667255e-01,-5.004462e-01,-8.455478e-01,-2.756589e-01,-8.746373e-01,-6.098789e-01,-8.808263e-01,-8.204568e-01,-5.998357e-01,-7.379981e-01,-6.274599e-01,-8.015607e-01
50%,-3.494235e-01,-5.004462e-01,-3.494974e-01,-2.756589e-01,-2.134189e-01,-1.455293e-01,2.643949e-01,-2.550316e-01,-4.808100e-01,-4.172382e-01,2.178877e-01,-1.789413e-01
75%,-7.215742e-02,3.715014e-01,1.066752e+00,-2.756589e-01,5.696029e-01,4.499863e-01,9.473991e-01,6.285651e-01,-1.237329e-01,2.395560e-01,8.347630e-01,5.484387e-01
max,1.004022e+01,3.859292e+00,2.467023e+00,3.627671e+00,2.805565e+00,3.511133e+00,1.167289e+00,3.226202e+00,1.780678e+00,1.913617e+00,1.657263e+00,3.839852e+00

## 4.모델링 : KNN

### (1) import

In [17]:
# 모델링용
from sklearn.neighbors import KNeighborsRegressor    

# 회귀모델 평가용
from sklearn.metrics import *

### (2) 모델선언

In [18]:
model = KNeighborsRegressor() # k : 기본값 5

In [19]:
x_train_s1.shape

(354, 12)

In [20]:
x_val_s1.shape

(152, 12)

### (3) 모델링(학습)

In [21]:
model.fit(x_train_s1,y_train)

KNeighborsRegressor()

### (4) 검증 : 예측

In [22]:
pred = model.predict(x_val_s1)
pred

array([19.5 , 13.88, 18.88, 30.2 , 14.92, 14.24, 24.06, 16.22,  8.72,
       19.08, 23.02, 22.82, 19.56, 16.2 , 19.66, 29.46, 10.56, 13.82,
       17.6 , 20.44, 21.8 , 19.68, 11.84, 34.54, 32.24, 43.84, 24.66,
       18.74, 19.34, 26.08, 23.  , 23.06, 22.02, 19.48, 11.2 , 13.14,
       14.34, 19.7 , 14.66, 32.44, 10.46, 11.9 , 18.38,  8.94, 14.24,
       29.42, 19.78, 12.5 , 14.76, 17.98, 22.4 , 11.18, 27.28, 29.24,
       24.02, 19.2 , 24.2 , 25.58, 25.46, 20.  , 14.8 , 14.02, 14.24,
       27.62, 21.8 , 18.52, 26.14, 20.16, 26.6 , 17.62, 13.3 , 23.26,
       11.32, 23.02, 24.98, 15.88, 15.3 , 10.28, 11.04, 24.86, 15.88,
       21.34, 18.6 , 33.82, 15.56, 11.82, 24.06, 21.46, 13.14, 34.8 ,
       21.34, 23.16, 23.16, 14.24, 14.1 , 24.18, 24.6 , 15.86, 13.38,
       22.64, 29.1 , 13.38, 40.92, 22.84, 21.42, 16.64, 41.16, 23.2 ,
       15.3 , 30.08, 15.7 , 12.48, 10.02, 21.2 , 24.72, 24.1 , 22.4 ,
       15.86, 18.92, 30.86, 31.34, 21.92, 24.66, 21.1 , 21.5 , 22.66,
        9.76, 21.66, 14.76, 17.  , 22.4 , 15.62, 21.82, 24.4 , 22.1 ,
       38.34, 23.54,  9.54, 26.5 , 14.6 , 30.2 , 31.48, 29.18, 21.74,
        8.84, 34.16, 16.96, 13.08, 15.44, 19.96, 14.46, 27.7 ])

### (5) 검증 : 평가

In [23]:
# RMSE
mean_squared_error(y_val,pred,squared=False)

4.227564933050456

In [24]:
# MAE
mean_absolute_error(y_val,pred)

3.035

In [25]:
# MAPE : 평균 오차율
mean_absolute_percentage_error(y_val,pred)

0.16339021011462934

In [26]:
# 1 - MAPE : 정확도
1 - mean_absolute_percentage_error(y_val,pred)

0.8366097898853706

## 5.Hyper Parameter

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

* n_neighbors : k 의 갯수. k가 달라지면 예측결과도 달라지고, 성능도 달라집니다!
* metric : 거리계산 방식.
    * euclidean : 유클리디안 거리 :  sqrt(a^2 + b^2)
    * manhattan : 맨하탄거리 : a + b

In [27]:
# model1 : n_neighbors = 10, metric = 'euclidean'
model1 = KNeighborsRegressor(n_neighbors = 10, metric = 'euclidean')
model1.fit(x_train_s1, y_train)
pred1 = model1.predict(x_val_s1)

In [28]:
# model2 : n_neighbors = 10, metric = 'manhattan'
model2 = KNeighborsRegressor(n_neighbors = 10, metric = 'manhattan')
model2.fit(x_train_s1, y_train)
pred2 = model2.predict(x_val_s1)

In [29]:
print(f'metric = euclidean : rmse {mean_squared_error(y_val, pred1, squared = False)}')
print(f'metric = manhattan : rmse {mean_squared_error(y_val, pred2, squared = False)}')

metric = euclidean : rmse 4.841955074901916
metric = manhattan : rmse 4.420933680260671

In [30]:
print(f'metric = euclidean : mae {mean_absolute_error(y_val, pred1)}')
print(f'metric = manhattan : mae {mean_absolute_error(y_val, pred2)}')

metric = euclidean : mae 3.462763157894737
metric = manhattan : mae 3.2408552631578953

In [31]:
print(f'metric = euclidean : mape {mean_absolute_percentage_error(y_val, pred1)}')
print(f'metric = manhattan : mape {mean_absolute_percentage_error(y_val, pred2)}')

metric = euclidean : mape 0.18505949742155064
metric = manhattan : mape 0.17819962243785456

## 6.연습문제
* 다음의 조건을 조정하며 모델을 생성하고 성능을 비교해 봅시다.
* 조건
    * 스케일링 데이터 : 하이퍼파라미터는 default로 두고, 스케일링 데이터만 달리하며 비교해 봅시다.
        * 정규화 : x_train_s1, x_val_s1
        * 표준화 : x_train_s2, x_val_s2
    * k : 
        * k 값을 1에서 50까지 1씩 증가시켜가며 
        * 성능 rmse, mae, mape를 구하고 최적의 k 값을 찾아 봅시다.

### (1) 스케일링 데이터 비교.

In [32]:
# 정규화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_s = scaler.fit_transform(x_train_s1)
x_val_s = scaler.transform(x_val_s1)

In [33]:
# 표준화
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler()
x_train_m = scaler2.fit_transform(x_train_s2)
x_val_m = scaler2.transform(x_val_s2)

In [35]:
for i in range(1,51):
    model1 = KNeighborsRegressor(n_neighbors=i,metric ='euclidean')
    model1.fit(x_train_s,y_train)
    pred1 = model1.predict(x_val_s)
    print(i)
    print(mean_squared_error(y_val,pred1,squared=False))
    print(mean_absolute_error(y_val, pred1))
    print(mean_absolute_percentage_error(y_val, pred1))
    print()

1
4.63010742173895
3.1039473684210526
0.18074016312196256

2
4.0323058082912
2.9444078947368424
0.1763761571857222

3
4.044070997635691
2.8313596491228066
0.17443802020335664

4
3.92634908092278
2.8565789473684204
0.17252783257960538

5
4.191138835309815
2.971710526315789
0.17378681288843553

6
4.233684929797602
2.9827850877192983
0.17141783812490544

7
4.3158879848467295
3.0534774436090224
0.1726398410302335

8
4.369443487425216
3.100904605263158
0.17451352578626841

9
4.292414581208583
3.081432748538012
0.1746013857619247

10
4.330149277237205
3.119407894736842
0.17609772232587223

11
4.2654264205275325
3.1316985645933015
0.17736639012692398

12
4.273866755425192
3.1201206140350877
0.17772604142268134

13
4.3180719186907925
3.144331983805668
0.18003479652485227

14
4.314213474411378
3.1380169172932333
0.1812596215967306

15
4.3525015997054615
3.161666666666667
0.18334006880079667

16
4.359811010312424
3.1608141447368414
0.18470359658480634

17
4.34232587752105
3.1542569659442723
0.1843518723216457

18
4.416748592421236
3.199488304093567
0.18600904242407762

19
4.480137292255378
3.256336565096953
0.18872980628032193

20
4.523414395791373
3.2641776315789475
0.18853956991804557

21
4.5275371464498875
3.2708646616541355
0.19017932168121782

22
4.578624947557489
3.2965610047846887
0.19194574616692006

23
4.614307318724951
3.331550343249428
0.19387841723914648

24
4.626208982869216
3.340433114035088
0.1938948984438625

25
4.649959558397992
3.354552631578948
0.19523630626900654

26
4.673238863590823
3.3688765182186238
0.1963268088013399

27
4.718671466333593
3.401754385964912
0.19865767096430714

28
4.754533167809116
3.4115366541353382
0.19947161205796318

29
4.797914290425474
3.4389745916515424
0.2019154932074602

30
4.833981013773272
3.433267543859649
0.20148042373771377

31
4.855815490972689
3.45195246179966
0.20295728015273048

32
4.894550634360112
3.4844777960526314
0.20468101942376205

33
4.93448651653508
3.506638755980861
0.2060765561028554

34
4.971215760395542
3.5296052631578947
0.20790691942590583

35
5.006070208919096
3.5612593984962406
0.20966654902209825

36
5.053974402910016
3.5982456140350876
0.2117674164173089

37
5.044053911715078
3.590949502133712
0.21198965410723894

38
5.09431802599219
3.623078254847645
0.2136283170978506

39
5.140405658060768
3.657607962213225
0.21624822618498105

40
5.190636056659855
3.709490131578947
0.22005669760983662

41
5.214278569499754
3.7311136071887034
0.22151536163982474

42
5.255881982231614
3.7560463659147874
0.22391123882228242

43
5.309610592746742
3.8033047735618113
0.22637180233512838

44
5.342934965215137
3.824132775119617
0.22814495657464096

45
5.363661799669566
3.8473684210526313
0.22955267511113017

46
5.393038366690392
3.865417620137299
0.23131459651272615

47
5.399100737235594
3.878079507278835
0.23282823989404725

48
5.436232827325135
3.9009320175438593
0.23462834303341773

49
5.454430366880759
3.9197368421052627
0.23641114779110128

50
5.483633001463249
3.9493947368421054
0.2389141637293219

In [37]:
for i in range(1,51):
    model1 = KNeighborsRegressor(n_neighbors=i,metric ='manhattan')
    model1.fit(x_train_s,y_train)
    pred1 = model1.predict(x_val_s)
    print(i)
    print(mean_squared_error(y_val,pred1,squared=False))
    print(mean_absolute_error(y_val, pred1))
    print(mean_absolute_percentage_error(y_val, pred1))
    print()

1
5.039625873749799
3.2927631578947367
0.18304369355511377

2
4.128276210924387
3.0276315789473687
0.1781161507748806

3
3.925124313597339
2.8651315789473686
0.1685252655580158

4
3.9497584869537476
2.838815789473684
0.16671307583290576

5
3.856097700225477
2.7005263157894737
0.15809548476908003

6
4.014418230338013
2.843530701754386
0.16356632260462067

7
4.04208426683479
2.9443609022556396
0.166707200893791

8
4.095895379989067
2.970230263157895
0.16564593594465185

9
4.116872346117865
2.9896929824561407
0.1680983411689843

10
4.174859279065583
3.047368421052632
0.17242277646921053

11
4.239932873790536
3.058433014354067
0.17405476018832022

12
4.251442125037557
3.0286732456140353
0.17265019743441967

13
4.2737075317159805
3.0304149797570847
0.17151680283963294

14
4.297557844141009
3.048825187969925
0.17284363679991538

15
4.376671243032843
3.088815789473684
0.1750714682756619

16
4.378641958049638
3.075534539473684
0.1752125931727578

17
4.475015121213982
3.1391640866873063
0.17763141057319412

18
4.475827476030737
3.1344298245614026
0.17818090956683844

19
4.538367985296748
3.187915512465373
0.1809333785166304

20
4.589322687528428
3.2336513157894737
0.18431477981021788

21
4.647929672304861
3.2619987468671674
0.18649771456999684

22
4.739215754626446
3.3009868421052633
0.18928370758007682

23
4.777538163988575
3.305263157894736
0.1894713506035932

24
4.8282075436744964
3.338322368421052
0.19185414784340835

25
4.8603029361943015
3.375105263157895
0.19373216802234042

26
4.882850664674892
3.3772773279352224
0.1940898872888023

27
4.951229073467914
3.429922027290448
0.19762315670039132

28
4.981775603261486
3.4465460526315788
0.19908855410951298

29
5.010898348521472
3.4647912885662433
0.20047556190412355

30
5.063355826151489
3.504254385964913
0.20254761734942814

31
5.101453454204861
3.532470288624788
0.20454814587329673

32
5.138538710384987
3.568791118421052
0.20725564862337018

33
5.186096770912434
3.5890151515151523
0.20866855480543706

34
5.206889660902394
3.6099845201238394
0.21013466833057082

35
5.204853308133061
3.6004511278195492
0.20990982497381702

36
5.24638285171049
3.6318165204678357
0.2117848838455522

37
5.274484869681422
3.6488086770981507
0.21283048885627567

38
5.3096858900831965
3.6606994459833793
0.21368442816516853

39
5.3290324736381685
3.6719804318488527
0.21532699463550134

40
5.38721220152653
3.729194078947369
0.21956966397981756

41
5.4172254197725795
3.763430680359435
0.2225285279698844

42
5.447225892444723
3.7872963659147874
0.22506992475925544

43
5.467287157706301
3.811520807833537
0.22648574143657293

44
5.498490376054241
3.847353468899522
0.23000927392960432

45
5.5204598656276085
3.8728947368421056
0.2325303510605197

46
5.540404420475426
3.902216819221968
0.2346283283314289

47
5.564349981784279
3.9207166853303477
0.23577499521747325

48
5.605720505927789
3.9494380482456144
0.23848664903106223

49
5.632461101451232
3.970985499462943
0.23920930885706457

50
5.653853764887879
3.9887236842105267
0.2404383570597864

In [40]:
for i in range(1,51):
    model2 = KNeighborsRegressor(n_neighbors=i,metric ='euclidean')
    model2.fit(x_train_m,y_train)
    pred2 = model2.predict(x_val_m)
    print(i)
    print(mean_squared_error(y_val,pred2,squared=False))
    print(mean_absolute_error(y_val, pred2))
    print(mean_absolute_percentage_error(y_val, pred2))
    print()

1
5.1797746852033715
3.4690789473684207
0.18525312449754464

2
4.281481697533669
3.0657894736842106
0.1644239146778844

3
3.899292370950407
2.8510964912280703
0.16187632686472572

4
4.104204960191822
2.901644736842105
0.15867625614103983

5
4.227564933050456
3.035
0.16339021011462934

6
4.433874126098064
3.1846491228070177
0.17040828142291925

7
4.48123878789268
3.27312030075188
0.1753946599415002

8
4.637504211588384
3.3605263157894742
0.17904467400192423

9
4.806153581421751
3.459137426900585
0.18363394496559407

10
4.841955074901916
3.462763157894737
0.18505949742155064

11
4.765400562228352
3.4440789473684212
0.18541955614486316

12
4.832377259115352
3.4795504385964913
0.1884393125851166

13
4.83889051476573
3.491902834008097
0.19000245813746786

14
4.789771243604228
3.4640037593984965
0.1890517723748572

15
4.731427433191335
3.4026754385964915
0.1877927358078493

16
4.741629896008722
3.3965460526315794
0.1888731480497419

17
4.8393650520207805
3.452089783281734
0.19149517044080236

18
4.873803855187795
3.4578947368421056
0.19219441055469952

19
4.883207051671184
3.4513850415512466
0.19273449011383254

20
4.937893588576537
3.49953947368421
0.19561589560489384

21
4.983239242705669
3.5447368421052627
0.19829108700974685

22
5.015251369845815
3.5661483253588515
0.1986245197480379

23
5.06151493522036
3.593192219679634
0.2006553221939027

24
5.132169737040595
3.635197368421052
0.20342485974055102

25
5.157277045720521
3.659894736842106
0.20471903658659085

26
5.21085944864697
3.694964574898786
0.20667189583501724

27
5.2004089466852905
3.6809210526315788
0.20622791115332212

28
5.217352640833577
3.68202537593985
0.20642629630204024

29
5.2400547940189215
3.6889972776769513
0.20735550471593242

30
5.271760937029769
3.693706140350877
0.20769565138632157

31
5.320681865358056
3.7342105263157896
0.20957333554042976

32
5.3546793830951485
3.7577097039473686
0.21184520284887895

33
5.385199881235812
3.7796850079744817
0.21328514795283238

34
5.405086971573966
3.791060371517028
0.21418701006370075

35
5.446466271285767
3.8048496240601506
0.21506984201492974

36
5.484728562190628
3.823501461988304
0.21595070025678167

37
5.524338190655503
3.8380512091038397
0.21780012300447787

38
5.5734585849469855
3.8783067867036007
0.22047866807565752

39
5.599212762676101
3.887263832658569
0.22128611403760803

40
5.616724471711107
3.9036348684210522
0.22253606669267753

41
5.6409653877096515
3.925625802310654
0.22433865617093451

42
5.671649269367574
3.949483082706766
0.22594219230587828

43
5.694684890651483
3.966906364749082
0.22741292097592175

44
5.73879476840924
3.999446770334928
0.22968793694063577

45
5.783205935308583
4.03187134502924
0.23256784502404615

46
5.808652146344975
4.050457665903889
0.23413736316886477

47
5.853224499254197
4.085764277715565
0.2365655773218694

48
5.8833290501629145
4.1283305921052635
0.23978980008449113

49
5.908477463081244
4.1496240601503755
0.24159448860450955

50
5.958595701744003
4.192157894736842
0.24476098990630568

In [41]:
for i in range(1,51):
    model2 = KNeighborsRegressor(n_neighbors=i,metric ='manhattan')
    model2.fit(x_train_m,y_train)
    pred2 = model2.predict(x_val_m)
    print(i)
    print(mean_squared_error(y_val,pred2,squared=False))
    print(mean_absolute_error(y_val, pred2))
    print(mean_absolute_percentage_error(y_val, pred2))
    print()

1
5.106626242339199
3.369736842105263
0.1816740693126233

2
4.00083667236584
2.9200657894736843
0.16010740643994345

3
4.02615081074681
2.8958333333333335
0.15436311279135345

4
3.962025747810808
2.792434210526316
0.1506956239997825

5
4.035930402091483
2.855394736842106
0.15260936931135793

6
4.183659428472912
3.0031798245614034
0.16303887605509967

7
4.221406943699924
3.07218045112782
0.16822166013863515

8
4.341930232217853
3.1263157894736846
0.1706481064758998

9
4.360413025664652
3.1671052631578953
0.1734508274903896

10
4.420933680260671
3.2408552631578953
0.17819962243785456

11
4.4940013664730545
3.2294258373205746
0.1770682246373557

12
4.532984216433226
3.225219298245614
0.1767781825639071

13
4.563963083927649
3.2232287449392714
0.17802645631874534

14
4.60748501527141
3.2015507518796995
0.1777593429992249

15
4.642175048539913
3.2147807017543863
0.1772621762426233

16
4.68740252091626
3.2569901315789473
0.17921664760191677

17
4.773908691814097
3.3037538699690403
0.1819946504310358

18
4.748010146287891
3.304861111111111
0.18250714583236902

19
4.821262405620134
3.324619113573407
0.18397001980165392

20
4.859207263562973
3.376743421052632
0.1867829109612917

21
4.883910284131387
3.388220551378447
0.1880718749173996

22
4.9475687237917185
3.413875598086125
0.18923789818706038

23
4.964176099698822
3.433094965675057
0.1915449950615388

24
5.020495957581056
3.475438596491228
0.19435607054479695

25
5.038132047328235
3.472421052631579
0.19445329041381165

26
5.063574591534731
3.4979251012145753
0.19647887978524628

27
5.106441103228425
3.532407407407408
0.19804832091818553

28
5.165055605628789
3.575046992481203
0.20128777707588896

29
5.222246015679064
3.6090063520871145
0.20365754066999936

30
5.245724331044278
3.624013157894737
0.20487129005867988

31
5.28809814667545
3.6518251273344653
0.2062858402430797

32
5.316399594310193
3.6752055921052627
0.2076291403175424

33
5.346095381413545
3.705821371610845
0.20897532997826254

34
5.3903911559252595
3.735758513931888
0.2121063740355962

35
5.433230297051179
3.7760714285714285
0.21423295708756598

36
5.474900117880095
3.807839912280702
0.2161816812595202

37
5.504120558641762
3.8396514935988617
0.21864638942926484

38
5.524230710725911
3.850657894736842
0.21996904406136247

39
5.542257420379162
3.861622807017544
0.2210518524215331

40
5.578375221057462
3.8913651315789473
0.22339909105733122

41
5.615728552433255
3.9175064184852375
0.2254084585555244

42
5.6619329316336575
3.9530231829573936
0.22873128504635992

43
5.666851076725622
3.964488984088127
0.23000297299466257

44
5.689411979838222
3.974865430622009
0.23109578135342884

45
5.70363040856934
3.993026315789474
0.23314408173251802

46
5.729421908159786
4.009339244851258
0.2341676913651638

47
5.766759361990956
4.043435050391937
0.23742014394435973

48
5.779098348021095
4.05764802631579
0.2387044245741519

49
5.816022802856054
4.088265306122449
0.24084489485391122

50
5.840476066572872
4.1027894736842105
0.24201965176763712

### (2) k 값